name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch code
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests using pytest
        run: pytest
  build-and-push-docker-image:
    name: Build/Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
          IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/ci-cd-webinar
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

          

